server:
  port: 8081
  servlet:
    context-path: /ms_practice

spring:
  data:
    mongodb:
      database: StudentDB
      host: localhost
      username: student
      password: 1234
      port: 27017
      uri: mongodb://student:1234@localhost:27017/StudentDB
      #uri: mongodb+srv://student:1234@cluster0.g9zwy.mongodb.net/StudentDB?retryWrites=true&w=majority
      #mongodb://scott:password!@server:port